server:
  port: 8095
spring:
  application:
    name: travel-message
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    password: 123456
    host: localhost
    port: 6379