server:
  port: 9091
spring:
  application:
    name: travel-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    password: 123456
  rabbitmq:
    addresses: 192.168.237.129
    username: root
    password: root
    virtual-host: /
  elasticsearch:
    rest:
      uris: http://localhost:9201